<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Event;
use App\Models\Community;
use Carbon\Carbon;

class EventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $communities = Community::all();
        
        $events = [
            [
                'title' => 'AI Summit Jakarta 2025',
                'subtitle' => 'Exploring the Future of Artificial Intelligence',
                'community_id' => 'ai-ml-community',
                'community_name' => 'AI & Machine Learning',
                'date' => Carbon::now()->addDays(15)->setTime(9, 0),
                'location' => 'Jakarta Convention Center',
                'image' => 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&h=600&fit=crop',
                'description' => 'Join us for the biggest AI summit in Jakarta featuring keynote speakers from leading tech companies, workshops on machine learning, and networking opportunities with AI professionals.',
                'category' => 'Technology Conference',
                'tags' => ['#AI', '#MachineLearning', '#TechSummit', '#Innovation'],
            ],
            [
                'title' => 'Book Club: Harry Potter Marathon',
                'subtitle' => 'A full day marathon discussing all seven Harry Potter books',
                'community_id' => 'literacy-circle',
                'community_name' => 'Literacy Circle',
                'date' => Carbon::now()->addDays(20)->setTime(14, 0),
                'location' => 'Periplus Bookstore, Jakarta',
                'image' => 'https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?w=800&h=600&fit=crop',
                'description' => 'A full day marathon discussing all seven Harry Potter books. Bring your favorite theories and cosplay as your favorite character!',
                'category' => 'Book Club',
                'tags' => ['#Books', '#HarryPotter', '#Reading', '#Community'],
            ],
            [
                'title' => 'Startup Pitch Night',
                'subtitle' => 'Where innovation meets investment',
                'community_id' => 'startup-hub-bandung',
                'community_name' => 'Startup Hub Bandung',
                'date' => Carbon::now()->addDays(10)->setTime(19, 0),
                'location' => 'Co-working Space Bandung',
                'image' => 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800&h=600&fit=crop',
                'description' => 'Present your startup idea to potential investors and get feedback from experienced entrepreneurs. Cash prizes for the best pitches!',
                'category' => 'Startup Event',
                'tags' => ['#Startup', '#Pitch', '#Investment', '#Entrepreneurship'],
            ],
            [
                'title' => 'Photography Workshop: Street Photography',
                'subtitle' => 'Capturing life in urban environments',
                'community_id' => 'photography-masters',
                'community_name' => 'Photography Masters',
                'date' => Carbon::now()->addDays(7)->setTime(8, 0),
                'location' => 'Old Town Jakarta',
                'image' => 'https://images.unsplash.com/photo-1606983340077-61f8b2d10a1b?w=800&h=600&fit=crop',
                'description' => 'Learn the art of street photography with professional photographers. Hands-on workshop covering composition, lighting, and storytelling through images.',
                'category' => 'Photography Workshop',
                'tags' => ['#Photography', '#StreetPhoto', '#Workshop', '#Urban'],
            ],
            [
                'title' => 'Eco-Friendly Living Expo',
                'subtitle' => 'Sustainable solutions for modern life',
                'community_id' => 'green-earth-movement',
                'community_name' => 'Green Earth Movement',
                'date' => Carbon::now()->addDays(25)->setTime(10, 0),
                'location' => 'Senayan City Mall',
                'image' => 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&h=600&fit=crop',
                'description' => 'Discover eco-friendly products, attend sustainability workshops, and learn how to reduce your carbon footprint in daily life.',
                'category' => 'Environmental Expo',
                'tags' => ['#Sustainability', '#EcoFriendly', '#Environment', '#GreenLiving'],
            ],
            [
                'title' => 'Digital Marketing Masterclass',
                'subtitle' => 'Advanced strategies for online growth',
                'community_id' => 'tech-innovators-jakarta',
                'community_name' => 'Tech Innovators Jakarta',
                'date' => Carbon::now()->addDays(12)->setTime(13, 30),
                'location' => 'WeWork SCBD',
                'image' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=600&fit=crop',
                'description' => 'Master the latest digital marketing techniques including SEO, social media marketing, and conversion optimization with industry experts.',
                'category' => 'Digital Marketing',
                'tags' => ['#DigitalMarketing', '#SEO', '#SocialMedia', '#Growth'],
            ],
            [
                'title' => 'Fitness Challenge: 5K Run',
                'subtitle' => 'Run for health, run for community',
                'community_id' => 'fitness-warriors',
                'community_name' => 'Fitness Warriors',
                'date' => Carbon::now()->addDays(8)->setTime(6, 0),
                'location' => 'Gelora Bung Karno',
                'image' => 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop',
                'description' => 'Join our community 5K run challenge. All fitness levels welcome! Free health check-up and healthy breakfast included.',
                'category' => 'Fitness Event',
                'tags' => ['#Running', '#Fitness', '#Health', '#Community'],
            ],
            [
                'title' => 'Blockchain Development Workshop',
                'subtitle' => 'Building decentralized applications',
                'community_id' => 'blockchain-developers',
                'community_name' => 'Blockchain Developers',
                'date' => Carbon::now()->addDays(18)->setTime(14, 0),
                'location' => 'Tech Hub Kuningan',
                'image' => 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&h=600&fit=crop',
                'description' => 'Learn to build smart contracts and DApps. Hands-on workshop covering Solidity, Web3.js, and blockchain deployment.',
                'category' => 'Technology Workshop',
                'tags' => ['#Blockchain', '#Cryptocurrency', '#SmartContracts', '#Web3'],
            ],
            [
                'title' => 'Culinary Tour: Indonesian Street Food',
                'subtitle' => 'Exploring authentic local flavors',
                'community_id' => 'culinary-explorers',
                'community_name' => 'Culinary Explorers',
                'date' => Carbon::now()->addDays(5)->setTime(17, 0),
                'location' => 'Jalan Sabang, Jakarta',
                'image' => 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&h=600&fit=crop',
                'description' => 'Guided tour of the best street food spots in Jakarta. Taste traditional dishes and learn about Indonesian culinary culture.',
                'category' => 'Food Tour',
                'tags' => ['#StreetFood', '#Indonesian', '#Culinary', '#FoodTour'],
            ],
            [
                'title' => 'Mental Health Awareness Workshop',
                'subtitle' => 'Breaking the stigma, building support',
                'community_id' => 'mental-health-advocates',
                'community_name' => 'Mental Health Advocates',
                'date' => Carbon::now()->addDays(22)->setTime(15, 0),
                'location' => 'Tzu Chi Center Jakarta',
                'image' => 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&h=600&fit=crop',
                'description' => 'Learn about mental health awareness, stress management techniques, and how to support friends and family dealing with mental health issues.',
                'category' => 'Mental Health',
                'tags' => ['#MentalHealth', '#Awareness', '#Support', '#Wellness'],
            ],
            [
                'title' => 'Travel Photography Expedition',
                'subtitle' => 'Capturing beauty of Indonesian landscapes',
                'community_id' => 'travel-enthusiasts',
                'community_name' => 'Travel Enthusiasts',
                'date' => Carbon::now()->addDays(30)->setTime(5, 0),
                'location' => 'Borobudur Temple, Yogyakarta',
                'image' => 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&h=600&fit=crop',
                'description' => '3-day photography expedition to capture sunrise at Borobudur, traditional markets, and local culture. All skill levels welcome.',
                'category' => 'Travel Photography',
                'tags' => ['#Travel', '#Photography', '#Borobudur', '#Culture'],
            ],
            [
                'title' => 'Fashion Design Competition',
                'subtitle' => 'Sustainable fashion for the future',
                'community_id' => 'fashion-forward',
                'community_name' => 'Fashion Forward',
                'date' => Carbon::now()->addDays(35)->setTime(16, 0),
                'location' => 'Fashion Week Jakarta',
                'image' => 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=800&h=600&fit=crop',
                'description' => 'Design competition focusing on sustainable and eco-friendly fashion. Showcase your creativity while promoting environmental consciousness.',
                'category' => 'Fashion Competition',
                'tags' => ['#Fashion', '#Sustainable', '#Design', '#Competition'],
            ],
            [
                'title' => 'Science Fair: Future Innovations',
                'subtitle' => 'Young minds shaping tomorrow',
                'community_id' => 'science-explorers',
                'community_name' => 'Science Explorers',
                'date' => Carbon::now()->addDays(28)->setTime(9, 0),
                'location' => 'BINUS University',
                'image' => 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800&h=600&fit=crop',
                'description' => 'Student science fair featuring innovative projects in robotics, biotechnology, and environmental science. Open to public.',
                'category' => 'Science Fair',
                'tags' => ['#Science', '#Innovation', '#Students', '#Technology'],
            ],
            [
                'title' => 'Documentary Film Screening',
                'subtitle' => 'Stories that change perspectives',
                'community_id' => 'film-cinema-society',
                'community_name' => 'Film & Cinema Society',
                'date' => Carbon::now()->addDays(14)->setTime(19, 30),
                'location' => 'Kineforum TIM',
                'image' => 'https://images.unsplash.com/photo-1489599424972-0d4b41805b42?w=800&h=600&fit=crop',
                'description' => 'Screening of award-winning documentary films followed by discussion with filmmakers and critics.',
                'category' => 'Film Screening',
                'tags' => ['#Documentary', '#Film', '#Cinema', '#Discussion'],
            ],
            [
                'title' => 'Volunteer Day: Community Garden',
                'subtitle' => 'Growing together for a better tomorrow',
                'community_id' => 'volunteer-network',
                'community_name' => 'Volunteer Network',
                'date' => Carbon::now()->addDays(9)->setTime(7, 0),
                'location' => 'Taman Suropati',
                'image' => 'https://images.unsplash.com/photo-1559027006-11b67b93ad94?w=800&h=600&fit=crop',
                'description' => 'Join us in creating a community garden. Plant vegetables, learn about urban farming, and contribute to food security initiatives.',
                'category' => 'Volunteer Activity',
                'tags' => ['#Volunteer', '#Community', '#Garden', '#Environment'],
            ],
            [
                'title' => 'Youth Leadership Summit',
                'subtitle' => 'Empowering the next generation',
                'community_id' => 'youth-empowerment',
                'community_name' => 'Youth Empowerment',
                'date' => Carbon::now()->addDays(40)->setTime(8, 30),
                'location' => 'University of Indonesia',
                'image' => 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800&h=600&fit=crop',
                'description' => 'Leadership development program for young people featuring workshops on public speaking, project management, and social impact.',
                'category' => 'Leadership Summit',
                'tags' => ['#Leadership', '#Youth', '#Development', '#Skills'],
            ],
            [
                'title' => 'Urban Farming Workshop',
                'subtitle' => 'Growing food in small spaces',
                'community_id' => 'urban-farmers',
                'community_name' => 'Urban Farmers',
                'date' => Carbon::now()->addDays(16)->setTime(10, 0),
                'location' => 'Rooftop Garden Kemang',
                'image' => 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=600&fit=crop',
                'description' => 'Learn vertical farming techniques, hydroponic systems, and how to grow your own food in apartments and small spaces.',
                'category' => 'Agriculture Workshop',
                'tags' => ['#UrbanFarming', '#Hydroponics', '#SustainableLiving', '#Food'],
            ],
            [
                'title' => 'Public Speaking Bootcamp',
                'subtitle' => 'Overcome fear, speak with confidence',
                'community_id' => 'public-speaking-club',
                'community_name' => 'Public Speaking Club',
                'date' => Carbon::now()->addDays(11)->setTime(13, 0),
                'location' => 'Toastmasters Center Jakarta',
                'image' => 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800&h=600&fit=crop',
                'description' => 'Intensive bootcamp to improve public speaking skills. Practice sessions, feedback, and techniques to overcome stage fright.',
                'category' => 'Communication Skills',
                'tags' => ['#PublicSpeaking', '#Communication', '#Confidence', '#Skills'],
            ],
            [
                'title' => 'Meditation Retreat Weekend',
                'subtitle' => 'Finding inner peace in busy world',
                'community_id' => 'meditation-mindfulness',
                'community_name' => 'Meditation & Mindfulness',
                'date' => Carbon::now()->addDays(21)->setTime(6, 0),
                'location' => 'Vihara Buddhagaya, Bogor',
                'image' => 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
                'description' => '2-day meditation retreat focusing on mindfulness practices, stress reduction, and mental clarity. All experience levels welcome.',
                'category' => 'Meditation Retreat',
                'tags' => ['#Meditation', '#Mindfulness', '#Retreat', '#Wellness'],
            ],
            [
                'title' => 'Local Business Networking Night',
                'subtitle' => 'Connecting entrepreneurs and small businesses',
                'community_id' => 'local-business-network',
                'community_name' => 'Local Business Network',
                'date' => Carbon::now()->addDays(13)->setTime(18, 30),
                'location' => 'Plaza Indonesia',
                'image' => 'https://images.unsplash.com/photo-1556745757-8d76bdb6984b?w=800&h=600&fit=crop',
                'description' => 'Network with local business owners, share experiences, and explore collaboration opportunities. Speed networking sessions included.',
                'category' => 'Business Networking',
                'tags' => ['#Networking', '#Business', '#Entrepreneurs', '#Local'],
            ],
            [
                'title' => 'Cultural Heritage Festival',
                'subtitle' => 'Celebrating Indonesian traditions',
                'community_id' => 'cultural-heritage',
                'community_name' => 'Cultural Heritage',
                'date' => Carbon::now()->addDays(45)->setTime(14, 0),
                'location' => 'Taman Mini Indonesia Indah',
                'image' => 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=600&fit=crop',
                'description' => 'Celebrate Indonesian cultural diversity with traditional performances, crafts demonstrations, and cultural exhibitions.',
                'category' => 'Cultural Festival',
                'tags' => ['#Culture', '#Heritage', '#Indonesian', '#Traditional'],
            ],
            [
                'title' => 'Women in Tech Conference',
                'subtitle' => 'Breaking barriers in technology',
                'community_id' => 'women-in-tech',
                'community_name' => 'Women in Tech',
                'date' => Carbon::now()->addDays(32)->setTime(9, 30),
                'location' => 'Microsoft Indonesia Office',
                'image' => 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&h=600&fit=crop',
                'description' => 'Conference featuring successful women in technology, career development workshops, and mentorship opportunities.',
                'category' => 'Technology Conference',
                'tags' => ['#WomenInTech', '#Technology', '#Career', '#Empowerment'],
            ],
            [
                'title' => 'Sports Analytics Workshop',
                'subtitle' => 'Data science meets sports performance',
                'community_id' => 'sports-analytics',
                'community_name' => 'Sports Analytics',
                'date' => Carbon::now()->addDays(26)->setTime(15, 30),
                'location' => 'Gelora Bung Karno Sports Complex',
                'image' => 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop',
                'description' => 'Learn how data analytics is revolutionizing sports performance, team strategies, and fan engagement.',
                'category' => 'Sports Technology',
                'tags' => ['#SportsAnalytics', '#DataScience', '#Sports', '#Performance'],
            ],
            [
                'title' => 'Creative Writing Workshop',
                'subtitle' => 'Unleashing your storytelling potential',
                'community_id' => 'creative-writing-guild',
                'community_name' => 'Creative Writing Guild',
                'date' => Carbon::now()->addDays(19)->setTime(16, 0),
                'location' => 'Gramedia Matraman',
                'image' => 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&h=600&fit=crop',
                'description' => 'Workshop for aspiring writers covering character development, plot structure, and publishing opportunities.',
                'category' => 'Writing Workshop',
                'tags' => ['#Writing', '#Storytelling', '#Creative', '#Publishing'],
            ],
            [
                'title' => 'Music Production Masterclass',
                'subtitle' => 'From idea to hit song',
                'community_id' => 'music-creators-studio',
                'community_name' => 'Music Creators Studio',
                'date' => Carbon::now()->addDays(24)->setTime(19, 0),
                'location' => 'Music Studio Kemang',
                'image' => 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=600&fit=crop',
                'description' => 'Learn music production techniques, mixing, and mastering from professional producers. Hands-on studio experience included.',
                'category' => 'Music Production',
                'tags' => ['#Music', '#Production', '#Studio', '#Audio'],
            ],
            [
                'title' => 'Language Exchange Festival',
                'subtitle' => 'Connecting cultures through language',
                'community_id' => 'language-exchange-hub',
                'community_name' => 'Language Exchange Hub',
                'date' => Carbon::now()->addDays(17)->setTime(10, 30),
                'location' => 'Erasmus Huis Jakarta',
                'image' => 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=600&fit=crop',
                'description' => 'Practice multiple languages with native speakers, cultural presentations, and international food fair.',
                'category' => 'Language Exchange',
                'tags' => ['#Languages', '#Culture', '#International', '#Exchange'],
            ],
            [
                'title' => 'Gaming Tournament: Esports Championship',
                'subtitle' => 'Compete for glory and prizes',
                'community_id' => 'gaming-community-indonesia',
                'community_name' => 'Gaming Community Indonesia',
                'date' => Carbon::now()->addDays(29)->setTime(12, 0),
                'location' => 'JIExpo Kemayoran',
                'image' => 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&h=600&fit=crop',
                'description' => 'Major esports tournament featuring popular games. Professional and amateur divisions with substantial prize pools.',
                'category' => 'Gaming Tournament',
                'tags' => ['#Gaming', '#Esports', '#Tournament', '#Competition'],
            ],
            [
                'title' => 'Digital Nomad Meetup',
                'subtitle' => 'Remote work, infinite possibilities',
                'community_id' => 'digital-nomads-indonesia',
                'community_name' => 'Digital Nomads Indonesia',
                'date' => Carbon::now()->addDays(6)->setTime(17, 30),
                'location' => 'GoWork Senayan',
                'image' => 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&h=600&fit=crop',
                'description' => 'Monthly meetup for digital nomads and remote workers. Share experiences, tips, and networking opportunities.',
                'category' => 'Digital Nomad',
                'tags' => ['#DigitalNomad', '#RemoteWork', '#Networking', '#Lifestyle'],
            ],
            [
                'title' => 'Art Exhibition: Contemporary Indonesian Art',
                'subtitle' => 'Exploring modern artistic expressions',
                'community_id' => 'art-design-collective',
                'community_name' => 'Art & Design Collective',
                'date' => Carbon::now()->addDays(37)->setTime(18, 0),
                'location' => 'National Gallery Indonesia',
                'image' => 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800&h=600&fit=crop',
                'description' => 'Exhibition showcasing contemporary Indonesian artists exploring themes of identity, culture, and modernization.',
                'category' => 'Art Exhibition',
                'tags' => ['#Art', '#Contemporary', '#Indonesian', '#Exhibition'],
            ],
        ];

        foreach ($events as $index => $event) {
            // Use existing community if available, otherwise use the predefined community_name
            if ($communities->count() > 0) {
                $community = $communities->random();
                $event['community_id'] = strtolower(str_replace(' ', '-', $community->name));
                $event['community_name'] = $community->name;
            }
            
            Event::create($event);
        }
    }
}